# Generated by Django 5.1.2 on 2026-08-20 07:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCareInstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('hand-wash', 'Hand Wash Only'), ('machine-wash', 'Machine Washable'), ('no-bleach', 'Do Not Bleach'), ('dry-shade', 'Dry in Shade'), ('dry-sun', 'Dry in Sun'), ('low-iron', 'Low Iron'), ('no-iron', 'Do Not Iron'), ('dry-clean', 'Dry Clean'), ('no-dry-clean', 'No Dry Clean'), ('store', 'Store Carefully'), ('delicate', 'Handle Delicately'), ('general', 'General Care')], default='general', max_length=30)),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_instructions', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Care Instruction',
                'verbose_name_plural': 'Product Care Instructions',
                'db_table': 'product_care_instruction',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Specification',
                'verbose_name_plural': 'Product Specifications',
                'db_table': 'product_specification',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
