# Generated by Django 5.1.2 on 2026-08-20 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_productcareinstruction_productspecification'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='is_color',
            field=models.BooleanField(default=False, help_text='Mark as a color attribute so its values show a name + hex swatch instead of plain text.'),
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='hex_code',
            field=models.CharField(blank=True, help_text='e.g. #C0392B — only used for color attributes.', max_length=7, null=True),
        ),
    ]
