# Generated by Django 5.1.2 on 2026-09-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_attribute_is_color_attributevalue_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/'),
        ),
    ]
